# Generated by Django 6.0.7 on 2026-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_title',
        ),
        migrations.AddField(
            model_name='book',
            name='sumary',
            field=models.TextField(null=True),
        ),
    ]
