# Generated by Django 6.0.7 on 2026-07-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_title_book_book_title_book_sumary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='book',
            name='sumary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
