# Generated by Django 6.0.7 on 2026-07-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_book_title_book_title_alter_book_sumary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='sumary',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='loan',
            name='effective_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
